language: python


matrix:
  include:
    - name: "Python 3.5 with newest dependency versions"
      env: ENVIRONMENT=.ci/environment_py35.yml
    - name: "Python 3.6 with newest dependency versions"
      env: ENVIRONMENT=.ci/environment_py36.yml
    - name: "Python 3.7 with newest dependency versions"
      env: ENVIRONMENT=.ci/environment_py37.yml

python:
  - 3.5
  - 3.6
  - 3.7

branches:
  only:
  - master

# services:
#
# matrix:
#  include:
#    - os: linux

   
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
#  - export GIT_FULL_HASH=`git rev-parse HEAD`
#  - conda config --set always_yes true
#  - conda update conda
#  - conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION matplotlib
#  - source activate testenv
#  - pip install -r requirements.txt
#  - conda install -n testenv -c conda-forge qtpy
#  - conda install -n testenv flake8
  - conda create -n --file $ENVIRONMENT
  - source activate testenv
  - conda list
  - conda install flake8

script:
  - python -c "import qtpy"
  - pytest tests/
  - flake8
#  - nosetests -v --rednose --cover-package=neutronbraggedge --with-coverage
#   - python tests/getdata.py
#   - python tests/ivenus/signon.py
#   - nosetests --exe

after_success:
 - codecov

notifications:
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b9d6dacd08d3e45e1b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
