language: python

matrix:
  include:
    - name: "Python 3.6 with newest dependency versions"
      env: ENVIRONMENT=.ci/environment_py36.yml

branches:
  only:
  - master

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

install:
#  - export GIT_FULL_HASH=`git rev-parse HEAD`
#  - conda config --set always_yes true
#  - conda update conda
#  - conda create -n testenv pip python=$TRAVIS_PYTHON_VERSION matplotlib
#  - source activate testenv
#  - pip install -r requirements.txt
#  - conda install -n testenv -c conda-forge qtpy
#  - conda install -n testenv flake8
  - conda env create --file $ENVIRONMENT
  - source activate testenv
  - conda list

script:
  - python -c "import qtpy"
  - pytest tests/
  - flake8
#  - nosetests -v --rednose --cover-package=neutronbraggedge --with-coverage
#   - python tests/getdata.py
#   - python tests/ivenus/signon.py
#   - nosetests --exe

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6b9d6dacd08d3e45e1b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
