name: testenv
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - astropy
  - matplotlib
  - numpy
  - pandas
  - pillow
  - plotly
  - psutil
  - pyqt
  - pytest
  - python=3.6
  - qt=5.9.6
  - qtpy=1.7.0
  - scipy
  - flake8
